const JsonData = [
  { "id": 1, "loggedBy": "player_alpha01", "message": "You're so bad at this game." },
  { "id": 2, "loggedBy": "player_beta02", "message": "Uninstall and never come back." },
  { "id": 3, "loggedBy": "player_gamma03", "message": "This team is full of idiots." },
  { "id": 4, "loggedBy": "player_delta04", "message": "Stop feeding, you're useless." },
  { "id": 5, "loggedBy": "player_epsilon05", "message": "I will report all of you." },
  { "id": 6, "loggedBy": "player_zeta06", "message": "You're trash lol." },
  { "id": 7, "loggedBy": "player_eta07", "message": "Why are you even playing?" },
  { "id": 8, "loggedBy": "player_theta08", "message": "Go learn the basics first." },
  { "id": 9, "loggedBy": "player_iota09", "message": "Worst player ever." },
  { "id": 10, "loggedBy": "player_kappa10", "message": "You just ruined the match." },

  { "id": 11, "loggedBy": "player_alpha11", "message": "Are you blind or what?" },
  { "id": 12, "loggedBy": "player_beta12", "message": "Nice throw, genius." },
  { "id": 13, "loggedBy": "player_gamma13", "message": "You don't belong here." },
  { "id": 14, "loggedBy": "player_delta14", "message": "Absolute noob team." },
  { "id": 15, "loggedBy": "player_epsilon15", "message": "You're embarrassing." },
  { "id": 16, "loggedBy": "player_zeta16", "message": "Delete the game please." },
  { "id": 17, "loggedBy": "player_eta17", "message": "This is painful to watch." },
  { "id": 18, "loggedBy": "player_theta18", "message": "Do something useful." },
  { "id": 19, "loggedBy": "player_iota19", "message": "You're the reason we lost." },
  { "id": 20, "loggedBy": "player_kappa20", "message": "Completely useless player." },

  { "id": 21, "loggedBy": "player_alpha21", "message": "I can't believe this team." },
  { "id": 22, "loggedBy": "player_beta22", "message": "Just quit already." },
  { "id": 23, "loggedBy": "player_gamma23", "message": "You play like a bot." },
  { "id": 24, "loggedBy": "player_delta24", "message": "So bad it's funny." },
  { "id": 25, "loggedBy": "player_epsilon25", "message": "You're dragging us down." },
  { "id": 26, "loggedBy": "player_zeta26", "message": "Nice job ruining everything." },
  { "id": 27, "loggedBy": "player_eta27", "message": "Worst decision ever." },
  { "id": 28, "loggedBy": "player_theta28", "message": "You have zero skills." },
  { "id": 29, "loggedBy": "player_iota29", "message": "Stop trolling." },
  { "id": 30, "loggedBy": "player_kappa30", "message": "Learn to play." },

  { "id": 31, "loggedBy": "player_alpha31", "message": "You're wasting everyone's time." },
  { "id": 32, "loggedBy": "player_beta32", "message": "This is a joke." },
  { "id": 33, "loggedBy": "player_gamma33", "message": "You are clueless." },
  { "id": 34, "loggedBy": "player_delta34", "message": "Don't queue again." },
  { "id": 35, "loggedBy": "player_epsilon35", "message": "You're hopeless." },
  { "id": 36, "loggedBy": "player_zeta36", "message": "Absolute disaster." },
  { "id": 37, "loggedBy": "player_eta37", "message": "You're just bad." },
  { "id": 38, "loggedBy": "player_theta38", "message": "Try harder next time." },
  { "id": 39, "loggedBy": "player_iota39", "message": "You're making it worse." },
  { "id": 40, "loggedBy": "player_kappa40", "message": "Why even try?" },

  { "id": 41, "loggedBy": "player_alpha41", "message": "So useless." },
  { "id": 42, "loggedBy": "player_beta42", "message": "This is pathetic." },
  { "id": 43, "loggedBy": "player_gamma43", "message": "You're terrible." },
  { "id": 44, "loggedBy": "player_delta44", "message": "Stop playing like that." },
  { "id": 45, "loggedBy": "player_epsilon45", "message": "You can't do anything right." },
  { "id": 46, "loggedBy": "player_zeta46", "message": "You're ruining my rank." },
  { "id": 47, "loggedBy": "player_eta47", "message": "This is so bad." },
  { "id": 48, "loggedBy": "player_theta48", "message": "You suck." },
  { "id": 49, "loggedBy": "player_iota49", "message": "Get better." },
  { "id": 50, "loggedBy": "player_kappa50", "message": "Just stop." },

  { "id": 51, "loggedBy": "player_alpha51", "message": "Worst gameplay ever." },
  { "id": 52, "loggedBy": "player_beta52", "message": "You're clueless." },
  { "id": 53, "loggedBy": "player_gamma53", "message": "Don't play ranked." },
  { "id": 54, "loggedBy": "player_delta54", "message": "You ruined it." },
  { "id": 55, "loggedBy": "player_epsilon55", "message": "So annoying." },
  { "id": 56, "loggedBy": "player_zeta56", "message": "This is garbage." },
  { "id": 57, "loggedBy": "player_eta57", "message": "No skills at all." },
  { "id": 58, "loggedBy": "player_theta58", "message": "You're useless." },
  { "id": 59, "loggedBy": "player_iota59", "message": "Terrible performance." },
  { "id": 60, "loggedBy": "player_kappa60", "message": "So bad." },

  { "id": 61, "loggedBy": "player_alpha61", "message": "You messed everything up." },
  { "id": 62, "loggedBy": "player_beta62", "message": "Embarrassing play." },
  { "id": 63, "loggedBy": "player_gamma63", "message": "Complete waste." },
  { "id": 64, "loggedBy": "player_delta64", "message": "Do better." },
  { "id": 65, "loggedBy": "player_epsilon65", "message": "So frustrating." },
  { "id": 66, "loggedBy": "player_zeta66", "message": "You're dragging us down." },
  { "id": 67, "loggedBy": "player_eta67", "message": "Why so bad?" },
  { "id": 68, "loggedBy": "player_theta68", "message": "Awful gameplay." },
  { "id": 69, "loggedBy": "player_iota69", "message": "Unbelievable." },
  { "id": 70, "loggedBy": "player_kappa70", "message": "Stop it." },

  { "id": 71, "loggedBy": "player_alpha71", "message": "This is not okay." },
  { "id": 72, "loggedBy": "player_beta72", "message": "Worst match ever." },
  { "id": 73, "loggedBy": "player_gamma73", "message": "You're so bad." },
  { "id": 74, "loggedBy": "player_delta74", "message": "Get out." },
  { "id": 75, "loggedBy": "player_epsilon75", "message": "Don't play again." },
  { "id": 76, "loggedBy": "player_zeta76", "message": "Useless team." },
  { "id": 77, "loggedBy": "player_eta77", "message": "Terrible choice." },
  { "id": 78, "loggedBy": "player_theta78", "message": "You're the worst." },
  { "id": 79, "loggedBy": "player_iota79", "message": "Completely bad." },
  { "id": 80, "loggedBy": "player_kappa80", "message": "So dumb." },

  { "id": 81, "loggedBy": "player_alpha81", "message": "What are you doing?" },
  { "id": 82, "loggedBy": "player_beta82", "message": "You failed again." },
  { "id": 83, "loggedBy": "player_gamma83", "message": "Worst decision." },
  { "id": 84, "loggedBy": "player_delta84", "message": "This is terrible." },
  { "id": 85, "loggedBy": "player_epsilon85", "message": "You're hopeless." },
  { "id": 86, "loggedBy": "player_zeta86", "message": "Can't believe you." },
  { "id": 87, "loggedBy": "player_eta87", "message": "You're bad." },
  { "id": 88, "loggedBy": "player_theta88", "message": "Noob play." },
  { "id": 89, "loggedBy": "player_iota89", "message": "Ridiculous." },
  { "id": 90, "loggedBy": "player_kappa90", "message": "So annoying." },

  { "id": 91, "loggedBy": "player_alpha91", "message": "You ruined it again." },
  { "id": 92, "loggedBy": "player_beta92", "message": "Terrible move." },
  { "id": 93, "loggedBy": "player_gamma93", "message": "This is trash." },
  { "id": 94, "loggedBy": "player_delta94", "message": "Stop this." },
  { "id": 95, "loggedBy": "player_epsilon95", "message": "You're awful." },
  { "id": 96, "loggedBy": "player_zeta96", "message": "Bad gameplay." },
  { "id": 97, "loggedBy": "player_eta97", "message": "You failed." },
  { "id": 98, "loggedBy": "player_theta98", "message": "So bad at this." },
  { "id": 99, "loggedBy": "player_iota99", "message": "You're useless again." },
  { "id": 100, "loggedBy": "player_kappa100", "message": "Worst performance." },

  { "id": 101, "loggedBy": "player_extra101", "message": "This is unacceptable." },
  { "id": 102, "loggedBy": "player_extra102", "message": "You're dragging us down again." },
  { "id": 103, "loggedBy": "player_extra103", "message": "Completely useless effort." },
  { "id": 104, "loggedBy": "player_extra104", "message": "You messed it up again." },
  { "id": 105, "loggedBy": "player_extra105", "message": "Worst teammate ever." },
  { "id": 106, "loggedBy": "player_extra106", "message": "Why are you like this?" },
  { "id": 107, "loggedBy": "player_extra107", "message": "This is a disaster." },
  { "id": 108, "loggedBy": "player_extra108", "message": "You're the problem." },
  { "id": 109, "loggedBy": "player_extra109", "message": "Stop ruining games." },
  { "id": 110, "loggedBy": "player_extra110", "message": "You have no idea." },
  { "id": 111, "loggedBy": "player_extra111", "message": "Absolutely terrible." },
  { "id": 112, "loggedBy": "player_extra112", "message": "You're not good." },
  { "id": 113, "loggedBy": "player_extra113", "message": "Worst skills ever." },
  { "id": 114, "loggedBy": "player_extra114", "message": "This is painful." },
  { "id": 115, "loggedBy": "player_extra115", "message": "You're doing nothing." },
  { "id": 116, "loggedBy": "player_extra116", "message": "Bad decisions." },
  { "id": 117, "loggedBy": "player_extra117", "message": "So useless again." },
  { "id": 118, "loggedBy": "player_extra118", "message": "Unreal stupidity." },
  { "id": 119, "loggedBy": "player_extra119", "message": "You can't play." },
  { "id": 120, "loggedBy": "player_extra120", "message": "Just leave the game." }
]
export default JsonData
